const nutrientConfig={
 ph:{label:'pH (CaCl₂)',aliases:['ph','ph cacl2','ph(cacl2)','ph_cacl2'],unit:'',low:5.5,high:6.5,decimals:1},
 p:{label:'Phosphorus (Colwell P)',aliases:['p','phosphorus','colwell p','colwell_p'],unit:'mg/kg',low:20,high:45,decimals:0},
 k:{label:'Potassium',aliases:['k','potassium'],unit:'cmol(+)/kg',low:.30,high:.65,decimals:2},
 s:{label:'Sulphur',aliases:['s','sulphur','sulfur'],unit:'mg/kg',low:6,high:12,decimals:1},
 oc:{label:'Organic Carbon',aliases:['oc','organic carbon','organic_carbon'],unit:'%',low:1,high:2,decimals:2},
 cec:{label:'CEC',aliases:['cec','cation exchange capacity'],unit:'cmol(+)/kg',low:8,high:18,decimals:1},
 zn:{label:'Zinc',aliases:['zn','zinc'],unit:'mg/kg',low:.8,high:2,decimals:1}
};

const demoPaddocks={type:'FeatureCollection',features:[
 {type:'Feature',properties:{paddock:'River'},geometry:{type:'Polygon',coordinates:[[[150.378,-24.381],[150.389,-24.381],[150.39,-24.389],[150.379,-24.39],[150.378,-24.381]]]}},
 {type:'Feature',properties:{paddock:'Home'},geometry:{type:'Polygon',coordinates:[[[150.389,-24.381],[150.401,-24.382],[150.4,-24.39],[150.39,-24.389],[150.389,-24.381]]]}},
 {type:'Feature',properties:{paddock:'North'},geometry:{type:'Polygon',coordinates:[[[150.401,-24.382],[150.414,-24.38],[150.42,-24.387],[150.417,-24.394],[150.4,-24.39],[150.401,-24.382]]]}},
 {type:'Feature',properties:{paddock:'Creek'},geometry:{type:'Polygon',coordinates:[[[150.379,-24.39],[150.39,-24.389],[150.392,-24.401],[150.382,-24.405],[150.377,-24.398],[150.379,-24.39]]]}},
 {type:'Feature',properties:{paddock:'Middle'},geometry:{type:'Polygon',coordinates:[[[150.39,-24.389],[150.4,-24.39],[150.404,-24.401],[150.392,-24.401],[150.39,-24.389]]]}},
 {type:'Feature',properties:{paddock:'East'},geometry:{type:'Polygon',coordinates:[[[150.4,-24.39],[150.417,-24.394],[150.42,-24.402],[150.404,-24.401],[150.4,-24.39]]]}},
 {type:'Feature',properties:{paddock:'South'},geometry:{type:'Polygon',coordinates:[[[150.377,-24.398],[150.382,-24.405],[150.392,-24.401],[150.395,-24.413],[150.38,-24.414],[150.377,-24.398]]]}},
 {type:'Feature',properties:{paddock:'Back'},geometry:{type:'Polygon',coordinates:[[[150.392,-24.401],[150.404,-24.401],[150.42,-24.402],[150.416,-24.414],[150.395,-24.413],[150.392,-24.401]]]}}
]};

const demoRows=[
 ['River',-24.384,150.381,2026,'0-10 cm',5.6,28,.42,8.2,1.21,11.8,1.2],['River',-24.386,150.385,2026,'0-10 cm',5.9,31,.46,8.9,1.34,12.8,1.4],['River',-24.388,150.387,2026,'0-10 cm',6.1,34,.50,9.2,1.41,13.5,1.6],
 ['Home',-24.384,150.394,2026,'0-10 cm',6.0,39,.57,10.2,1.63,14.7,1.7],['Home',-24.387,150.397,2026,'0-10 cm',6.3,44,.64,11.4,1.84,15.6,1.9],
 ['North',-24.385,150.407,2026,'0-10 cm',5.0,14,.24,4.8,.82,6.9,.5],['North',-24.389,150.412,2026,'0-10 cm',5.4,18,.30,5.5,.94,7.9,.7],
 ['Creek',-24.395,150.383,2026,'0-10 cm',5.4,21,.31,6.6,1.04,9.1,.9],['Creek',-24.4,150.387,2026,'0-10 cm',5.8,27,.39,7.8,1.2,10.4,1.1],
 ['Middle',-24.395,150.397,2026,'0-10 cm',5.7,25,.39,7.8,1.2,10.9,1.2],['Middle',-24.399,150.401,2026,'0-10 cm',5.9,29,.43,8.4,1.35,12.3,1.4],
 ['East',-24.396,150.408,2026,'0-10 cm',6.5,48,.68,13.4,1.94,19.2,2.2],['East',-24.4,150.414,2026,'0-10 cm',6.9,56,.76,15.0,2.22,21.2,2.6],
 ['South',-24.406,150.385,2026,'0-10 cm',5.2,16,.26,5.2,.89,7.6,.6],['South',-24.411,150.39,2026,'0-10 cm',5.6,20,.32,6.4,1.05,8.8,.8],
 ['Back',-24.406,150.401,2026,'0-10 cm',6.2,35,.51,10.8,1.51,13.9,1.6],['Back',-24.41,150.409,2026,'0-10 cm',6.6,41,.59,12.2,1.71,15.1,1.8]
].map((r,i)=>({paddock:r[0],latitude:r[1],longitude:r[2],year:r[3],depth:r[4],ph:r[5],p:r[6],k:r[7],s:r[8],oc:r[9],cec:r[10],zn:r[11],sample_id:`S${String(i+1).padStart(3,'0')}`}));

let map=L.map('map',{zoomControl:true}).setView([-24.397,150.399],14);
let satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:20,attribution:'Tiles © Esri'}).addTo(map);
let street=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'});
let paddockGeoJSON=demoPaddocks, soilRows=demoRows, paddockLayer, sampleLayer=L.layerGroup().addTo(map), selected=null;

const $=id=>document.getElementById(id);
Object.entries(nutrientConfig).forEach(([k,v])=>{const o=document.createElement('option');o.value=k;o.textContent=v.label;$('nutrientSelect').appendChild(o)});

function norm(s){return String(s??'').trim().toLowerCase().replace(/[_-]+/g,' ').replace(/\s+/g,' ')}
function findField(row,names){for(const key of Object.keys(row)){if(names.includes(norm(key)))return key}return null}
function numeric(v){if(v===null||v===undefined||v==='')return null;const n=Number(String(v).replace(/,/g,''));return Number.isFinite(n)?n:null}
function status(v,c){if(v==null)return'No data';const span=c.high-c.low;if(v<c.low-span*.55)return'Very low';if(v<c.low)return'Low';if(v<=c.high)return'Adequate';if(v<=c.high+span*.55)return'High';return'Very high'}
function color(s){return {'Very low':'#b63b3b','Low':'#e28a47','Adequate':'#4f945f','High':'#4d7fa8','Very high':'#684e93','No data':'#9aa49d'}[s]}
function format(v,c){if(v==null)return'—';return `${Number(v).toFixed(c.decimals)}${c.unit?' '+c.unit:''}`}
function currentRows(){return soilRows.filter(r=>($('yearSelect').value==='all'||String(r.year)===$('yearSelect').value)&&($('depthSelect').value==='all'||String(r.depth)===$('depthSelect').value))}
function paddockNameFromFeature(f){return f.properties?.paddock??f.properties?.PADDOCK??f.properties?.name??f.properties?.Name??f.properties?.NAME??'Unnamed paddock'}
function aggregate(){const key=$('nutrientSelect').value,c=nutrientConfig[key],groups={};for(const r of currentRows()){const name=String(r.paddock||'').trim();const v=numeric(r[key]);if(!name||v==null)continue;(groups[name]??=[]).push(v)}const out={};for(const [name,vals] of Object.entries(groups)){out[name]={avg:vals.reduce((a,b)=>a+b,0)/vals.length,min:Math.min(...vals),max:Math.max(...vals),count:vals.length,status:null};out[name].status=status(out[name].avg,c)}return out}
function refreshFilters(){const years=[...new Set(soilRows.map(r=>r.year).filter(v=>v!==undefined&&v!==null&&v!==''))].sort((a,b)=>b-a),depths=[...new Set(soilRows.map(r=>r.depth).filter(Boolean))];$('yearSelect').innerHTML='<option value="all">All years</option>'+years.map(y=>`<option value="${y}">${y}</option>`).join('');$('depthSelect').innerHTML='<option value="all">All depths</option>'+depths.map(d=>`<option value="${d}">${d}</option>`).join('');if(years.includes(2026))$('yearSelect').value='2026';}
function updateThresholdInputs(){const c=nutrientConfig[$('nutrientSelect').value];$('lowThreshold').value=c.low;$('highThreshold').value=c.high}
function renderLegend(){const c=nutrientConfig[$('nutrientSelect').value];$('legend').innerHTML=['Very low','Low','Adequate','High','Very high'].map(s=>`<span class="legend-item"><i class="swatch" style="background:${color(s)}"></i>${s}</span>`).join('');$('mapTitle').textContent=`${c.label} nutrient map`;}
function renderMetrics(){const key=$('nutrientSelect').value,c=nutrientConfig[key],rows=currentRows(),vals=rows.map(r=>numeric(r[key])).filter(v=>v!=null),agg=aggregate(),alerts=Object.values(agg).filter(x=>['Low','Very low'].includes(x.status)).length;const paddocks=paddockGeoJSON?.features?.length||0;const farmArea='—';const avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null;$('metrics').innerHTML=[['Paddocks',paddocks],['Samples',rows.length],['Avg '+c.label,format(avg,c)],['Low alerts',alerts],['Years',new Set(soilRows.map(r=>r.year)).size],['Farm area',farmArea]].map(([a,b])=>`<div class="metric"><span>${a}</span><strong>${b}</strong></div>`).join('')}
function renderPaddocks(){const key=$('nutrientSelect').value,c=nutrientConfig[key],agg=aggregate(),opacity=Number($('opacityRange').value)/100;if(paddockLayer)map.removeLayer(paddockLayer);paddockLayer=L.geoJSON(paddockGeoJSON,{style:f=>{const a=agg[paddockNameFromFeature(f)];return{color:'#fff',weight:2,fillColor:color(a?.status||'No data'),fillOpacity:opacity}},onEachFeature:(f,l)=>{const name=paddockNameFromFeature(f),a=agg[name];l.bindTooltip(name,{permanent:true,direction:'center',className:'paddock-label'});l.on('click',()=>{selected={type:'paddock',name,data:a};renderSelection()});}});if($('displaySelect').value!=='samples')paddockLayer.addTo(map)}
function renderSamples(){sampleLayer.clearLayers();if($('displaySelect').value==='paddocks')return;const key=$('nutrientSelect').value,c=nutrientConfig[key];for(const r of currentRows()){const lat=numeric(r.latitude),lng=numeric(r.longitude),v=numeric(r[key]);if(lat==null||lng==null)continue;const s=status(v,c);const marker=L.circleMarker([lat,lng],{radius:6,color:'#fff',weight:2,fillColor:color(s),fillOpacity:.95,className:'sample-marker'}).addTo(sampleLayer);marker.bindTooltip(`${r.sample_id||'Sample'} · ${format(v,c)}`);marker.on('click',()=>{selected={type:'sample',row:r};renderSelection()})}}
function renderSummary(){const key=$('nutrientSelect').value,c=nutrientConfig[key],agg=aggregate();$('summaryBody').innerHTML=Object.entries(agg).sort((a,b)=>a[1].avg-b[1].avg).map(([name,a])=>`<tr><td>${name}</td><td>${a.count}</td><td>${format(a.avg,c)}</td><td>${format(a.min,c)} – ${format(a.max,c)}</td><td><span style="color:${color(a.status)};font-weight:800">${a.status}</span></td></tr>`).join('')||'<tr><td colspan="5">No matching data.</td></tr>'}
function renderSelection(){const key=$('nutrientSelect').value,c=nutrientConfig[key];if(!selected){$('selectionDetails').innerHTML='Select a paddock or sample.';return}if(selected.type==='paddock'){const a=selected.data;$('selectionDetails').innerHTML=`<h3>${selected.name}</h3><span class="badge">${a?.status||'No data'}</span><div class="kv"><div><span>${c.label}</span><strong>${format(a?.avg,c)}</strong></div><div><span>Samples</span><strong>${a?.count??0}</strong></div><div><span>Lowest</span><strong>${format(a?.min,c)}</strong></div><div><span>Highest</span><strong>${format(a?.max,c)}</strong></div></div>`}else{const r=selected.row,v=numeric(r[key]),s=status(v,c);$('selectionDetails').innerHTML=`<h3>${r.sample_id||'Soil sample'}</h3><span class="badge">${s}</span><div class="kv"><div><span>Paddock</span><strong>${r.paddock||'—'}</strong></div><div><span>${c.label}</span><strong>${format(v,c)}</strong></div><div><span>Year</span><strong>${r.year||'—'}</strong></div><div><span>Depth</span><strong>${r.depth||'—'}</strong></div></div>`}}
function renderAll(){renderLegend();renderMetrics();renderPaddocks();renderSamples();renderSummary();renderSelection()}

function standardiseRows(raw){return raw.map((row,i)=>{const out={sample_id:null,paddock:null,latitude:null,longitude:null,year:null,depth:null};const sample=findField(row,['sample id','sample','sampleid','id']),pad=findField(row,['paddock','paddock name','field','block']),lat=findField(row,['latitude','lat','y']),lng=findField(row,['longitude','lon','lng','long','x']),year=findField(row,['year','sampling year']),date=findField(row,['sampling date','sample date','date']),depth=findField(row,['depth','sample depth']),depthFrom=findField(row,['sample depth from']),depthTo=findField(row,['sample depth to']);out.sample_id=sample?row[sample]:`S${i+1}`;out.paddock=pad?row[pad]:'';out.latitude=validLat(row[lat]);out.longitude=validLng(row[lng]);out.year=year?row[year]:(date?yearFromValue(row[date]):'');out.depth=depth?row[depth]:(depthFrom||depthTo?makeDepth(row[depthFrom],row[depthTo]):'');for(const [nk,c] of Object.entries(nutrientConfig)){const f=findField(row,c.aliases.map(norm));out[nk]=f?numericResult(row[f],false,true):null}return out}).filter(r=>r.paddock||r.latitude!=null||r.longitude!=null)}

let pendingExcel=null;
const importMetaFields=[
 {key:'sample_id',label:'Sample ID',defaults:['Sample ID']},
 {key:'sample_name',label:'Sample Name',defaults:['Sample Name']},
 {key:'grower',label:'Grower Name',defaults:['Grower Name']},
 {key:'customer',label:'Customer Name',defaults:['Customer Name']},
 {key:'paddock',label:'Paddock Name',defaults:['Paddock Name','Paddock']},
 {key:'sampling_date',label:'Sampling Date',defaults:['Sampling Date']},
 {key:'depth_from',label:'Depth From',defaults:['Sample Depth From']},
 {key:'depth_to',label:'Depth To',defaults:['Sample Depth To']},
 {key:'crop',label:'Crop',defaults:['Crop']},
 {key:'test_code',label:'Test Code',defaults:['Test Code']},
 {key:'latitude',label:'Latitude',defaults:['Latitude']},
 {key:'longitude',label:'Longitude',defaults:['Longitude']}
];
const importNutrients=[
 {key:'ph',label:'pH (CaCl₂)',defaults:['pH (1:5 CaCl2)','pH (1:5 CaCl2) ']},
 {key:'p',label:'Phosphorus (Colwell)',defaults:['Phosphorus (Colwell)']},
 {key:'k',label:'Potassium (Amm-acet.)',defaults:['Potassium (Amm-acet.)'],unit:'cmol(+)/kg'},
 {key:'s',label:'Sulphur (KCl40)',defaults:['Sulphur (KCl40)']},
 {key:'oc',label:'Organic Carbon (W&B)',defaults:['Organic Carbon (W&B)']},
 {key:'cec',label:'Cation Exchange Capacity',defaults:['Cation Exch. Cap.','Cation Exchange Capacity (BaCl/NH4Cl)']},
 {key:'zn',label:'Zinc (DTPA)',defaults:['Zinc (DTPA)']}
];
function validLat(v){const n=numericResult(v,true,true);return n!=null&&n>=-90&&n<=90?n:null}
function validLng(v){const n=numericResult(v,true,true);return n!=null&&n>=-180&&n<=180?n:null}
function numericResult(v,treat248,parseLimits){if(v===null||v===undefined||String(v).trim()==='')return null;let txt=String(v).trim();if(treat248&&txt==='248')return null;if(parseLimits)txt=txt.replace(/^[<>≤≥]\s*/,'');const n=Number(txt.replace(/,/g,''));return Number.isFinite(n)?n:null}
function yearFromValue(v){if(v==null||v==='')return'';if(v instanceof Date&&!isNaN(v))return v.getFullYear();const t=String(v).trim();let m=t.match(/\b(19|20)\d{2}\b/);if(m)return Number(m[0]);const d=new Date(t);return isNaN(d)?'':d.getFullYear()}
function makeDepth(a,b){const aa=String(a??'').trim(),bb=String(b??'').trim();if(aa&&bb)return `${aa}-${bb} cm`;if(aa)return `From ${aa} cm`;if(bb)return `To ${bb} cm`;return''}
function excelCol(n){let s='';for(let x=n+1;x;x=Math.floor((x-1)/26))s=String.fromCharCode(65+(x-1)%26)+s;return s}
function buildColumns(matrix,headerRow,unitsRow){const headers=matrix[headerRow-1]||[],units=unitsRow>0?(matrix[unitsRow-1]||[]):[];return headers.map((h,i)=>({index:i,id:String(i),header:String(h??'').trim()||`Column ${excelCol(i)}`,unit:String(units[i]??'').trim(),display:`${excelCol(i)} · ${String(h??'').trim()||'Unnamed'}${String(units[i]??'').trim()?` [${String(units[i]).trim()}]`:''}`}))}
function findBestColumn(columns,names,unit){const wanted=names.map(norm);let candidates=columns.filter(c=>wanted.includes(norm(c.header)));if(unit){const byUnit=candidates.find(c=>norm(c.unit)===norm(unit));if(byUnit)return byUnit}return candidates[0]||null}
function selectHTML(id,label,columns,defaults,unit){const best=findBestColumn(columns,defaults,unit);return `<label>${label}<select id="${id}"><option value="">— Do not import —</option>${columns.map(c=>`<option value="${c.id}" ${best&&best.id===c.id?'selected':''}>${escapeHtml(c.display)}</option>`).join('')}</select></label>`}
function escapeHtml(v){return String(v??'').replace(/[&<>\"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch]))}
function getWizardStructure(){return {sheet:$('wizardSheet').value,headerRow:Math.max(1,Number($('wizardHeaderRow').value)||1),unitsRow:Math.max(0,Number($('wizardUnitsRow').value)||0),dataRow:Math.max(1,Number($('wizardDataRow').value)||1)}}
function refreshWizardMappings(){if(!pendingExcel)return;const st=getWizardStructure(),matrix=pendingExcel.matrices[st.sheet]||[],columns=buildColumns(matrix,st.headerRow,st.unitsRow);pendingExcel.columns=columns;$('wizardMetaMappings').innerHTML=importMetaFields.map(f=>selectHTML(`map_meta_${f.key}`,f.label,columns,f.defaults)).join('');$('wizardNutrientMappings').innerHTML=importNutrients.map(f=>selectHTML(`map_nut_${f.key}`,f.label,columns,f.defaults,f.unit)).join('');renderWizardPreview();const exact=columns.some(c=>norm(c.header)==='sample id')&&columns.some(c=>norm(c.header)==='paddock name')&&columns.some(c=>norm(c.header)==='ph (1:5 cacl2)');$('wizardDetection').innerHTML=exact?'<span class="mapping-status">AGnVET soil export format detected.</span> Row 1 headings + row 2 units have been recognised. Default mappings have been filled in.':'Spreadsheet structure detected. Review the mappings below before importing.'}
function renderWizardPreview(){if(!pendingExcel)return;const st=getWizardStructure(),matrix=pendingExcel.matrices[st.sheet]||[],cols=pendingExcel.columns||buildColumns(matrix,st.headerRow,st.unitsRow),rows=matrix.slice(st.dataRow-1,st.dataRow+3);const shown=cols.slice(0,14);$('wizardPreview').innerHTML=`<table class="wizard-table"><thead><tr>${shown.map(c=>`<th>${escapeHtml(c.header)}${c.unit?`<br><small>${escapeHtml(c.unit)}</small>`:''}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${shown.map(c=>`<td>${escapeHtml(r[c.index]??'')}</td>`).join('')}</tr>`).join('')}</tbody></table><div class="wizard-note">Preview shows the first ${shown.length} columns. The supplied export contains ${cols.length} columns in total.</div>`}
function openExcelWizard(file,workbook){const matrices={};for(const name of workbook.SheetNames){matrices[name]=XLSX.utils.sheet_to_json(workbook.Sheets[name],{header:1,defval:'',raw:false})}pendingExcel={fileName:file.name,workbook,matrices,columns:[]};$('wizardSheet').innerHTML=workbook.SheetNames.map(n=>`<option value="${escapeHtml(n)}">${escapeHtml(n)}</option>`).join('');if(workbook.SheetNames.includes('Soil Samples Result'))$('wizardSheet').value='Soil Samples Result';$('wizardHeaderRow').value=1;$('wizardUnitsRow').value=2;$('wizardDataRow').value=3;$('wizardTreat248').checked=true;$('wizardParseLessThan').checked=true;$('wizardFileInfo').textContent=`${file.name} · ${workbook.SheetNames.length} worksheet${workbook.SheetNames.length===1?'':'s'}`;$('excelWizard').classList.remove('hidden');refreshWizardMappings()}
function closeExcelWizard(){$('excelWizard').classList.add('hidden');pendingExcel=null}
function mappedColumn(id){const v=$(id)?.value;return v===''||v==null?null:Number(v)}
function applyExcelWizard(){if(!pendingExcel)return;const st=getWizardStructure(),matrix=pendingExcel.matrices[st.sheet]||[],treat248=$('wizardTreat248').checked,parseLimits=$('wizardParseLessThan').checked;const meta={};for(const f of importMetaFields)meta[f.key]=mappedColumn(`map_meta_${f.key}`);const nuts={};for(const f of importNutrients)nuts[f.key]=mappedColumn(`map_nut_${f.key}`);const rows=[];for(let ri=st.dataRow-1;ri<matrix.length;ri++){const r=matrix[ri]||[],out={};for(const [k,ci] of Object.entries(meta))out[k]=ci==null?'':r[ci];out.sample_id=String(out.sample_id||`S${ri-st.dataRow+2}`);out.paddock=String(out.paddock||'').trim();out.latitude=meta.latitude==null?null:validLat(treat248&&String(r[meta.latitude]).trim()==='248'?'':r[meta.latitude]);out.longitude=meta.longitude==null?null:validLng(treat248&&String(r[meta.longitude]).trim()==='248'?'':r[meta.longitude]);out.year=yearFromValue(out.sampling_date);out.depth=makeDepth(out.depth_from,out.depth_to);for(const [k,ci] of Object.entries(nuts))out[k]=ci==null?null:numericResult(r[ci],treat248,parseLimits);if(out.paddock||Object.values(nuts).some(ci=>ci!=null&&numericResult(r[ci],treat248,parseLimits)!=null)||out.latitude!=null||out.longitude!=null)rows.push(out)}soilRows=rows;refreshFilters();selected=null;$('status').textContent=`Imported ${soilRows.length} soil sample row${soilRows.length===1?'':'s'} from ${pendingExcel.fileName}. ${$('wizardTreat248').checked?'Placeholder value 248 was treated as no result.':''}`;closeExcelWizard();renderAll()}

$('soilInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.name.toLowerCase().endsWith('.csv')){const text=await file.text();const workbook=XLSX.read(text,{type:'string'});openExcelWizard(file,workbook)}else{const buf=await file.arrayBuffer();const workbook=XLSX.read(buf,{type:'array',cellDates:true});openExcelWizard(file,workbook)}}catch(err){console.error(err);$('status').textContent='Could not read the soil test file. Check the spreadsheet format and headings.'}})

$('wizardCloseBtn').addEventListener('click',closeExcelWizard);$('wizardCancelBtn').addEventListener('click',closeExcelWizard);$('wizardImportBtn').addEventListener('click',applyExcelWizard);$('wizardSheet').addEventListener('change',refreshWizardMappings);['wizardHeaderRow','wizardUnitsRow','wizardDataRow'].forEach(id=>$(id).addEventListener('change',refreshWizardMappings));

$('boundaryInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const ext=file.name.toLowerCase().split('.').pop();let gj;if(ext==='zip'){gj=await shp(await file.arrayBuffer())}else if(ext==='kml'){const xml=new DOMParser().parseFromString(await file.text(),'text/xml');gj=toGeoJSON.kml(xml)}else{gj=JSON.parse(await file.text())}if(Array.isArray(gj))gj={type:'FeatureCollection',features:gj.flatMap(x=>x.features||[])};paddockGeoJSON=gj;if(paddockLayer)map.removeLayer(paddockLayer);const tmp=L.geoJSON(gj);map.fitBounds(tmp.getBounds(),{padding:[20,20]});$('status').textContent=`Loaded ${gj.features?.length||0} paddock features from ${file.name}.`;renderAll()}catch(err){console.error(err);$('status').textContent='Could not read paddock boundaries. For Shapefile upload a ZIP containing .shp, .shx and .dbf files.'}})

$('nutrientSelect').addEventListener('change',()=>{updateThresholdInputs();selected=null;renderAll()});$('yearSelect').addEventListener('change',()=>{selected=null;renderAll()});$('depthSelect').addEventListener('change',()=>{selected=null;renderAll()});$('displaySelect').addEventListener('change',renderAll);$('opacityRange').addEventListener('input',renderPaddocks);$('satelliteToggle').addEventListener('change',e=>{if(e.target.checked){if(map.hasLayer(street))map.removeLayer(street);satellite.addTo(map)}else{if(map.hasLayer(satellite))map.removeLayer(satellite);street.addTo(map)}});$('applyThresholdBtn').addEventListener('click',()=>{const c=nutrientConfig[$('nutrientSelect').value];c.low=Number($('lowThreshold').value);c.high=Number($('highThreshold').value);renderAll()});$('reportBtn').addEventListener('click',()=>window.print());$('loadDemoBtn').addEventListener('click',()=>{paddockGeoJSON=demoPaddocks;soilRows=demoRows;selected=null;$('farmName').value='Demo Farm';refreshFilters();map.fitBounds(L.geoJSON(demoPaddocks).getBounds(),{padding:[20,20]});$('status').textContent='Demo farm reloaded.';renderAll()});

refreshFilters();updateThresholdInputs();map.fitBounds(L.geoJSON(demoPaddocks).getBounds(),{padding:[20,20]});renderAll();
